name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Go Test
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Run
        run: go test --cover

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Go Lint
        uses: actions/checkout@v1

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
